/* === Mostly Generated by Gemini === */

/* Add accordions to sections */
function handleSections() {
  const accordionSections = document.querySelectorAll(".make-accordion");

  accordionSections.forEach(function (section) {
    const heading = section.querySelector("h1, h2, h3, h4, h5, h6");
    if (!heading) return;

    const details = document.createElement("details");
    details.classList.add("accordion");

    if (section.classList.contains("classref-section")) {
      details.classList.add("classref-accordion");
    }

    if (!section.classList.contains("close")) {
      details.setAttribute("open", "");
    }

    const summary = document.createElement("summary");

    const children = Array.from(section.children);
    const bodyElements = children.filter((child) => child !== heading);

    summary.appendChild(heading);
    details.appendChild(summary);

    bodyElements.forEach(function (element) {
      details.appendChild(element);
    });

    section.appendChild(details);
  });
}

/* Reimplement sidebar functionality from Godot Docs (godot.css) */
function handleSidebar() {
  window.addEventListener("keydown", function (event) {
    if (event.key === "/") {
      const searchField = document.querySelector(
        "#rtd-search-form input[type=text]",
      );
      if (searchField && document.activeElement !== searchField) {
        searchField.focus();
        searchField.select();
        event.preventDefault();
      }
    }
  });

  let hasCurrent = false;
  const menuHeaders = document.querySelectorAll(
    ".wy-menu-vertical .caption[role=heading]",
  );

  menuHeaders.forEach((it) => {
    const connectedMenu = it.nextElementSibling;
    if (!connectedMenu) return;

    it.addEventListener(
      "click",
      () => {
        if (connectedMenu.classList.contains("active")) {
          connectedMenu.classList.remove("active");
          it.classList.remove("active");
        } else {
          connectedMenu.classList.add("active");
          it.classList.add("active");
        }

        menuHeaders.forEach((ot) => {
          if (ot !== it && ot.classList.contains("active")) {
            if (ot.nextElementSibling) {
              ot.nextElementSibling.classList.remove("active");
            }
            ot.classList.remove("active");
          }
        });
      },
      true,
    );

    if (
      connectedMenu.classList.contains("current") ||
      connectedMenu.querySelector(".current")
    ) {
      connectedMenu.classList.add("active");
      it.classList.add("active");
      hasCurrent = true;
    }
  });

  // if (!hasCurrent && menuHeaders.length > 0) {
  //   menuHeaders[0].classList.add("active");
  //   if (menuHeaders[0].nextElementSibling) {
  //     menuHeaders[0].nextElementSibling.classList.add("active");
  //   }
  // }
}

/* Add styling to api-ref */
function handleReference() {
  Array.from(document.getElementsByClassName("reference")).forEach((ref) => {
    if (!ref.innerHTML.includes("^")) {
      return;
    }

    ref.classList.add("api-ref");
    ref.innerHTML = "<code>" + ref.innerHTML.replace("^", "") + "</code>";
  });
}

document.addEventListener("DOMContentLoaded", () => {
  handleSidebar();
  handleSections();
  handleReference();

  // handleSidebar();
});
